name: UPM-CI $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

# Pipeline should be manually queued
trigger: none
pr: none

parameters:
- name: useVersionOverride
  displayName: Override Version?
  type: boolean
  default: false
- name: versionOverride
  displayName: Package Version?
  type: string

variables:
  packageDirectory: "./artifacts/upm"

steps:
  - checkout: self

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  - template: templates/upm.yml
    parameters:
      publishToFeed: true
      useVersionOverride: $(useVersionOverride)
      versionOverride: $(versionOverride)

